I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/options.rpy", line 67, in script
    define config.main_menu_music_loop = True  # Зацикливание
  File "renpy/common/000namespaces.rpy", line 34, in set
    setattr(self.nso, name, value)
Exception: config.main_menu_music_loop is not a known configuration variable.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/options.rpy", line 67, in script
    define config.main_menu_music_loop = True  # Зацикливание
  File "C:\Users\lalka\Downloads\renpy-8.3.3-sdk\renpy\ast.py", line 2235, in execute
    self.set()
  File "C:\Users\lalka\Downloads\renpy-8.3.3-sdk\renpy\ast.py", line 2253, in set
    ns.set(self.varname, value)
  File "renpy/common/000namespaces.rpy", line 34, in set
    setattr(self.nso, name, value)
  File "C:\Users\lalka\Downloads\renpy-8.3.3-sdk\renpy\defaultstore.py", line 101, in __setattr__
    raise Exception('config.%s is not a known configuration variable.' % (name))
Exception: config.main_menu_music_loop is not a known configuration variable.

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.3.24111502
In the Shade of the Walnut Tree 0.1
Wed Mar 26 11:35:14 2025
